from collections.abc import Sequence
from datetime import datetime
from typing import Protocol

from optimus_backend.domain.entities import (
    AuditEventRecord,
    BillingSchedulerRunRecord,
    BillingCycleClosureRecord,
    ExecutionRecord,
    InvoiceRecord,
    InvoiceStatusTransitionRecord,
    InvoiceItemRecord,
    MemoryEntry,
    PlanDefinitionRecord,
    SubtaskRecord,
    SubscriptionPlanChangeRecord,
    SubscriptionRecord,
    UsageHistoryRecord,
    UserRecord,
    ApiKeyRecord,
)


class ExecutionRepository(Protocol):
    def create(self, record: ExecutionRecord) -> None: ...
    def update(self, record: ExecutionRecord) -> None: ...
    def get(self, execution_id: str) -> ExecutionRecord | None: ...
    def list_recent(self, limit: int = 50) -> Sequence[ExecutionRecord]: ...


class SubtaskRepository(Protocol):
    def create_many(self, subtasks: list[SubtaskRecord]) -> None: ...
    def update(self, subtask: SubtaskRecord) -> None: ...
    def list_by_execution(self, execution_id: str) -> Sequence[SubtaskRecord]: ...


class AuditRepository(Protocol):
    def append(self, event: AuditEventRecord) -> None: ...
    def list_by_execution(self, execution_id: str) -> Sequence[AuditEventRecord]: ...


class MemoryRepository(Protocol):
    def add(self, entry: MemoryEntry) -> None: ...
    def list_for_project(self, project_id: str, status: str | None = None) -> Sequence[MemoryEntry]: ...
    def approve(self, entry_id: str) -> None: ...
    def latest_by_type(self, project_id: str, entry_type: str) -> MemoryEntry | None: ...


class SessionRepository(Protocol):
    def save(self, session_id: str, user_id: str, ttl_seconds: int) -> None: ...
    def get_user_id(self, session_id: str) -> str | None: ...
    def delete(self, session_id: str) -> None: ...


class UserRepository(Protocol):
    def find_by_email(self, email: str) -> UserRecord | None: ...
    def find_by_id(self, user_id: str) -> UserRecord | None: ...


class JobQueue(Protocol):
    def enqueue_execution(self, execution_id: str) -> None: ...


class LockManager(Protocol):
    def acquire(self, key: str, ttl_seconds: int) -> bool: ...
    def release(self, key: str) -> None: ...


class RateLimiter(Protocol):
    def allow(self, project_id: str, tool_name: str, project_limit: int, tool_limit: int, ttl_seconds: int = 60) -> bool: ...


class UsageMeter(Protocol):
    def consume(self, project_id: str, plan_id: str, units: int = 1) -> tuple[bool, int, int]: ...
    def current(self, project_id: str, plan_id: str) -> tuple[int, int]: ...


class BillingReadModel(Protocol):
    def list_active_plans(self) -> Sequence[PlanDefinitionRecord]: ...
    def get_plan(self, plan_id: str) -> PlanDefinitionRecord | None: ...
    def get_active_subscription(self, project_id: str) -> SubscriptionRecord | None: ...
    def list_invoices(self, project_id: str) -> Sequence[InvoiceRecord]: ...
    def list_invoice_items(self, invoice_id: str) -> Sequence[InvoiceItemRecord]: ...
    def usage_history(self, project_id: str, date_from: datetime, date_to: datetime) -> Sequence[UsageHistoryRecord]: ...
    def list_plan_changes(self, project_id: str) -> Sequence[SubscriptionPlanChangeRecord]: ...
    def list_cycle_closures(self, project_id: str) -> Sequence[BillingCycleClosureRecord]: ...
    def list_active_subscriptions_due(self, as_of: datetime) -> Sequence[SubscriptionRecord]: ...
    def list_invoice_status_transitions(self, invoice_id: str) -> Sequence[InvoiceStatusTransitionRecord]: ...
    def list_scheduler_runs(self, limit: int = 20, offset: int = 0) -> Sequence[BillingSchedulerRunRecord]: ...
    def get_latest_scheduler_run(self) -> BillingSchedulerRunRecord | None: ...
    def list_scheduler_alerts(self, limit: int = 20) -> Sequence[BillingSchedulerRunRecord]: ...


class BillingCommandModel(Protocol):
    def create_subscription(self, project_id: str, plan_id: str, actor_id: str = "system") -> SubscriptionRecord: ...
    def activate_subscription(self, project_id: str, actor_id: str = "system") -> SubscriptionRecord: ...
    def create_or_activate_subscription(self, project_id: str, plan_id: str, actor_id: str = "system") -> SubscriptionRecord: ...
    def change_plan(self, project_id: str, new_plan_id: str) -> SubscriptionPlanChangeRecord: ...
    def cancel_subscription(self, project_id: str) -> SubscriptionRecord: ...
    def close_billing_cycle(
        self,
        project_id: str,
        period_start: datetime,
        period_end: datetime,
        actor_id: str = "system",
    ) -> InvoiceRecord: ...
    def update_invoice_status(self, invoice_id: str, to_status: str, actor_id: str = "system") -> InvoiceRecord: ...
    def record_scheduler_run(self, run: BillingSchedulerRunRecord) -> None: ...


class ApiKeyRepository(Protocol):
    def create(self, record: ApiKeyRecord) -> None: ...
    def find_active_by_prefix(self, key_prefix: str) -> ApiKeyRecord | None: ...
    def list_by_project(self, project_id: str) -> Sequence[ApiKeyRecord]: ...
    def get(self, key_id: str) -> ApiKeyRecord | None: ...
    def revoke(self, key_id: str, revoked_at: datetime) -> ApiKeyRecord | None: ...
    def touch_last_used(self, key_id: str, used_at: datetime) -> None: ...
