from collections.abc import Sequence
from typing import Protocol

from optimus_backend.domain.entities import AuditEventRecord, ExecutionRecord, MemoryEntry, SubtaskRecord, UserRecord


class ExecutionRepository(Protocol):
    def create(self, record: ExecutionRecord) -> None: ...
    def update(self, record: ExecutionRecord) -> None: ...
    def get(self, execution_id: str) -> ExecutionRecord | None: ...
    def list_recent(self, limit: int = 50) -> Sequence[ExecutionRecord]: ...


class SubtaskRepository(Protocol):
    def create_many(self, subtasks: list[SubtaskRecord]) -> None: ...
    def update(self, subtask: SubtaskRecord) -> None: ...
    def list_by_execution(self, execution_id: str) -> Sequence[SubtaskRecord]: ...


class AuditRepository(Protocol):
    def append(self, event: AuditEventRecord) -> None: ...
    def list_by_execution(self, execution_id: str) -> Sequence[AuditEventRecord]: ...


class MemoryRepository(Protocol):
    def add(self, entry: MemoryEntry) -> None: ...
    def list_for_project(self, project_id: str, status: str | None = None) -> Sequence[MemoryEntry]: ...
    def approve(self, entry_id: str) -> None: ...


class SessionRepository(Protocol):
    def save(self, session_id: str, user_id: str, ttl_seconds: int) -> None: ...
    def get_user_id(self, session_id: str) -> str | None: ...
    def delete(self, session_id: str) -> None: ...


class UserRepository(Protocol):
    def find_by_email(self, email: str) -> UserRecord | None: ...
    def find_by_id(self, user_id: str) -> UserRecord | None: ...


class JobQueue(Protocol):
    def enqueue_execution(self, execution_id: str) -> None: ...


class LockManager(Protocol):
    def acquire(self, key: str, ttl_seconds: int) -> bool: ...
    def release(self, key: str) -> None: ...
